apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: default
spec:
  selector:
    app: database
  type: LoadBalancer

  ports:
  - name: db-service
    protocol: TCP
    port: 1521
    targetPort: 1521

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pv-claim
  namespace: default
  labels:
    app: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  database       
  namespace: default
  labels:
    app:  database
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  template:
    metadata:
      labels:
        app:  database
    spec:
      securityContext: 
        runAsUser: 54321
        runAsGroup: 54321
        fsGroup: 54321
      volumes:
      - name: database-persistent-storage
        persistentVolumeClaim:
          claimName: database-pv-claim
      containers:
      - name: oracle-xe
        image: gvenzl/oracle-xe:21.3.0
        resources:
          limits:
            cpu: 1000m
            memory: 3000Mi
        env:
          - name: ORACLE_PASSWORD
            value: holamundo
          - name: APP_USER
            value: appuser
          - name: APP_USER_PASSWORD
            value: josue
        ports:
        - containerPort:  1521
          name:  database
        volumeMounts: 
        - name: database-persistent-storage
          mountPath: /opt/oracle/oradata

---
